name: Local CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-webapi:
    runs-on: [self-hosted, webapi]
    steps:
      - uses: actions/checkout@v3
      - name: Build webapi Docker Image
        run: docker build -t ragwebapi:latest -f RagWebApi-Tests/RagWebApi/Dockerfile .

  build-client:
    runs-on: [self-hosted, client]
    steps:
      - uses: actions/checkout@v3
      - name: Build Rag Client Docker Image
        run: docker build -t RagClient-frontend:latest -f RagClient/Dockerfile .

  deploy:
    runs-on: [self-hosted, docker]
    needs: [build-webapi, build-client]
    steps:
      - uses: actions/checkout@v3
      - name: Check Docker Version
        run: docker --Version
      - name: Start Containers of Docker Compose
        run: docker-compose up -d
